@MusicApi_HostAddress = https://localhost:7042

GET {{MusicApi_HostAddress}}/artists/query/?name=Nirvana
Accept: application/json

###

GET {{MusicApi_HostAddress}}/min/artists/query/?name=Nirvana
Accept: application/json

###
